Resources:
  RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: ${env:RDS_USERNAME}_${env:STAGE}
      MasterUserPassword: ${env:DB_PASSWORD}
#      Port: ${env:DB_PORT}
      DBSubnetGroupName:
        Ref: ServerlessSubnetGroup
      Engine: aurora-mysql
      EnableHttpEndpoint: true
      EngineVersion: 5.7.mysql_aurora.2.08.0
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 4
        MinCapacity: 2
        SecondsUntilAutoPause: 300
      DatabaseName: ${self:custom.AURORA.DB_NAME}
      BackupRetentionPeriod: 3
      DBClusterParameterGroupName: !Ref AuroraRDSClusterParameter
      VpcSecurityGroupIds:
        - !Ref RdsSecurityGroup
  AuroraRDSClusterParameter:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Parameter group for the Serverless Aurora RDS DB.
      Family: aurora-mysql5.7
      Parameters:
        character_set_database: "utf8mb4"
        character_set_server: "utf8mb4"
        collation_connection: "utf8mb4_unicode_ci"
        collation_server: "utf8mb4_unicode_ci"
Outputs:
  RDSCluster:
    Value: {"Ref": RDSCluster}
    Export:
      Name: RDSCluster-${env:STAGE}
  RDSClusterHost:
    Value:
      'Fn::GetAtt': [ RDSCluster, Endpoint.Address ]
    Export:
      Name: RDSCluster-host-${env:STAGE}
